services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network

  celery_worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./app:/app/app
    env_file:
      - .env

    depends_on:
      - redis
      - web
    networks:
      - app_network

  ngrok:
    image: ngrok/ngrok
    command: http --log stdout web:8000 # Ensure logs go to stdout
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
